"""
Django settings for reten_ecas project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
# from dotenv import load_dotenv

# load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d))4cmz4@t6&d%llm-5z-u6@7a@m!avdpx+9fil&d(7ug1aw=y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap5',
    'home',
    'ausenciaDepartamentales',
    'usuariosSatra',
    'modelos',
    'encuesta',
    'modelosBD',
    'gestion',
    # 'django_auth_adfs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django_auth_adfs.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'reten_ecas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'reten_ecas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'db_asistencia',
        'USER': 'djangoreten',
        'PASSWORD': '123',
        'HOST': "DESKTOP-QCP5VO2\\SQLEXPRESS",
        'PORT': '',
        'COLLATION': 'Modern_Spanish_CI_AS',
        'OPTIONS':{
            'driver': 'SQL Server Native Client 10.0',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'home.Usuario'

AUTHENTICATION_BACKENDS = [
    # 'django_auth_adfs.backend.AdfsAuthCodeBackend',
    'django.contrib.auth.backends.ModelBackend',  # Este backend es necesario para otros métodos de autenticación, como el panel de administración de Django
]

# Configure django to redirect users to the right URL for login
# LOGIN_URL = "django_auth_adfs:login"
# LOGIN_REDIRECT_URL = "/"

# AUTH_ADFS = {
#     'SERVER': 'https://login.microsoftonline.com/29fc6e2a-49bf-4002-a939-01b8edcb0aed/oauth2/v2.0/',
#     'CLIENT_ID': '7fc27ef4-1b64-48f5-b07a-40ef723cbb63',
#     'RELYING_PARTY_ID': 'http://localhost:8000',  # URL de tu aplicación Django
#     'CLAIM_MAPPING': {'first_name': 'given_name', 'last_name': 'family_name', 'email': 'email'},
#     'AUDIENCE': 'https://graph.microsoft.com', # Esto puede variar según tus necesidades específicas
#     'CLIENT_SECRET': '29fc6e2a-49bf-4002-a939-01b8edcb0aed', # Tu Id. de secreto
#     'USERNAME_CLAIM': 'email', # Specify the claim to use as the username
# }


# Client secret is not public information. Should store it as an environment variable.

# client_id = os.getenv('client_id')
# client_secret = os.getenv('client_secret')
# tenant_id = os.getenv('tenant_id')

client_id = '7fc27ef4-1b64-48f5-b07a-40ef723cbb63'
client_secret = '4bd13772-7327-465d-be5d-4d4a52995ac5'
tenant_id = '29fc6e2a-49bf-4002-a939-01b8edcb0aed'

# AUTH_ADFS = {
#     'AUDIENCE': client_id,
#     'CLIENT_ID': client_id,
#     'CLIENT_SECRET': client_secret,
#     # 'CLAIM_MAPPING': {
#     #     'first_name': 'given_name',
#     #     'last_name': 'family_name',
#     #     'email': 'email'
#     # },
#     # 'GROUPS_CLAIM': 'roles',
#     'MIRROR_GROUPS': True,
#     # 'USERNAME_CLAIM': 'email',  # Especifica el atributo de reclamación que deseas utilizar como nombre de usuario
#     'TENANT_ID': tenant_id,
#     'RELYING_PARTY_ID': client_id
# }

AUTH_ADFS = {
    'SERVER': 'https://login.microsoftonline.com/adc11501-d885-4fea-a7ff-96723b15d25b/oauth2/v2.0/',
    'CLIENT_ID': 'TU_CLIENT_ID',
    'RELYING_PARTY_ID': 'http://localhost:8000',  # URL de tu aplicación Django
    'USERNAME_CLAIM': 'email',  # Especifica el atributo de reclamación que deseas utilizar como nombre de usuario
    'AUDIENCE': 'https://graph.microsoft.com',
    'CLIENT_SECRET': '738bb499-d152-4883-beea-51260f43de6d', # Tu Id. de secreto
    'CLAIMS': {
        'email': 'email',
        'first_name': 'given_name',
        'last_name': 'family_name',
    }
}